spring:
  application:
    name: fj-hw-9

application:
  categories-url: https://kudago.com/public-api/v1.4/place-categories
  locations-url: https://kudago.com/public-api/v1.4/locations
  events-url: https://kudago.com/public-api/v1.4/events

  dictionary-init-task-schedule: 1s
  fixed-thread-pool-size: 6
  scheduled-thread-pool-size: 1

management:
  endpoints:
    web:
      exposure:
        include: metrics
